---
- name: Instalar Nginx
  import_tasks: nginx_installation.yml
  tags: 
    - deploy
    - installation

- name: Configuring NGINX HTTP Server to communicate with QRadar
  import_tasks: configure_nginx.yml
  tags:
    - deploy
    - configuration
