---
- name: Update repository
  apt:
    update_cache: yes

- name: Install Rsyslog
  apt:
    name: rsyslog
    state: present

- name: Enable Rsyslog
  systemd:
    state: started
    name: rsyslog.service
    enabled: yes
  
