---
- name: Update repository
  apt:
    update_cache: yes

- name: Install Auditd
  apt:
    name: auditd
    state: present

- name: Start and enable Auditd
  systemd:
    state: started
    name: auditd.service
    enabled: yes
