---
- name: Copy rsyslog config file
  template:
    src: rsyslog.j2
    dest: /etc/rsyslog.conf
    backup: yes

- name: reload Rsyslog configuration
  systemd:
    state: restarted
    name: rsyslog.service
