---
- hosts: testing
  become: yes
  become_method: sudo
  roles:
    - suricata

#- hosts: mysql
#  become: yes
#  become_method: sudo
#  roles:
#    - mariadb

#- hosts: docker
#  become: yes
#  become_method: sudo
#  roles:
#    - docker
    
#- hosts: rabbitmq
#  become: yes
#  become_method: sudo
#  roles:
#    - rabbitmq

#- hosts: webgoat
#  become: yes
#  become_method: sudo
#  roles:
#    - webgoat

#- hosts: firewall
#  become: yes
#  become_method: sudo
#  roles:
#    - nginx
#    - suricata
#    - iptables